version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.example
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.example
    restart: unless-stopped
  admin-panel:
    build: ./admin-panel
    ports:
      - "8000:8000"
    env_file:
      - ./admin-panel/.env.example
    restart: unless-stopped
  portal:
    build: ./portal
    ports:
      - "8080:8080"
    env_file:
      - ./portal/.env.example
    restart: unless-stopped
