version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3000"
    env_file:
      - .env.production
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ehb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
