version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: ehb-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ehb123456
      MONGO_INITDB_DATABASE: ehb_database
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: ehb-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ehb123456
      ME_CONFIG_MONGODB_URL: mongodb://admin:ehb123456@mongodb:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
