name: EHB Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend, admin-panel, portal]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm install
      - name: Build (if Next.js)
        if: matrix.service != 'backend'
        run: |
          cd ${{ matrix.service }}
          npm run build
      - name: Test (if available)
        run: |
          cd ${{ matrix.service }}
          if [ -f package.json ] && jq -e '.scripts.test' package.json > /dev/null; then npm test; else echo "No tests"; fi